name: The Identity Platform for Developers
title: Okta Developer
email: developers@okta.com
description: > # this means to ignore newlines until "baseurl:"
  Secure, scalable, and highly available authentication and user management for any app.
baseurl: ""
url: "http://developer.okta.com"
# url: "http://localhost:4000"
twitter_username: okta
github_username:  oktadeveloper

gems:
  - jekyll-redirect-from

# -- standard exclusions
exclude: [Gemfile, Gemfile.lock, README.md]

source: _source
destination: _site

markdown: kramdown
markdown_ext: md

kramdown:
  syntax_highlighter: rouge
  toc_levels: 1..3

permalink: /blog/:year/:month/:day/:title

support_phone_number: "1-888-722-7871"
github_base_url: "https://github.com/okta/okta.github.io/tree/master/_source/"
github_edit_url: "https://github.com/okta/okta.github.io/edit/master/_source/"
get_started_url: "https://www.okta.com/developer/signup"
stack_overflow_forum_url: "http://stackoverflow.com/search?q=okta"

ga_ua_id: "UA-15777010-3"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
        - "/search.json"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

include: [_static]

sass:
    sass_dir: _sass

collections:
  standards:
    output: true
  code:
    output: true
  use_cases:
    output: true
  reference:
    output: true
  3rd_party_notices:
    output: true
  docs:
    output: true
    permalink: /:collection/:path:output_ext

defaults:
  -
    scope:
      collection: slides
    values:
      layout: documentation
  -
    scope:
      collection: code
    values:
      layout: software
  -
    scope:
      collection: reference
    values:
      layout: documentation
